version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      # - 32400:32400/tcp
      - 80:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Sao_Paulo
      # - PLEX_CLAIM=<claim_token>
      # - ADVERTISE_IP=http://<127.0.0.1>/
    hostname: PlexServer
    volumes:
      - /home/ec2/plex/config:/config
      - /home/ec2/plex/transcode:/transcode
      - /home/ec2/plex/media:/data